### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by Philip-Clark**
Add Issue templates for bugs, Suggestions, and "Other" issues. More templates should be added

### CODE REVIEW

**Comment by Philip-Clark** [comment]
@MarchandMD shared [this repo](https://github.com/stevemao/github-issue-templates) with a lot of good templates. Feel free to suggest some to be added and I'll do my best to add them.

**Review by MarchandMD — APPROVED** [review]
LGTM; Perhaps the "Desktop" and "Smartphone" sections on the bug reports are overkill, but I'm not gonna hold this PR up; Better to have something to iterate on first

**Comment by Philip-Clark** [comment]
@MarchandMD
I can remove the smartphone and desktop section in favor of a simple browser section. Good call

**Review by MarchandMD — APPROVED** [review]
I like these updates; make it easier to start the conversation surrounding an issue. If additional clarity is needed, it should be on us to either seek clarity or dismiss the issue

**Pull request merged**
