### PR TITLE
Feat/contributors

### PR DESCRIPTION
**Pull request by Lofty-Brambles**
Mainly, fixing some linting issues and centering the title for a nicer read.

### CODE REVIEW

**Review by Philip-Clark — APPROVED** [review]

**Review by Philip-Clark — DISMISSED** [review]
Shouldn't we submit a PR for the tech stack before creating the boilerplate with a certain technology? I think these changes are better reflected as two PRs. One modifies the contribution guide, and the other proposes the addition of Vite as a tech.

**Comment by Lofty-Brambles** [comment]
> Shouldn't we submit a PR for the tech stack before creating the boilerplate with a certain technology? I think these changes are better reflected as two PRs. One modifies the contribution guide, and the other proposes the addition of Vite as a tech.

@Philip-Clark Where did I add a tech stack in this PR?

**Review by Philip-Clark — APPROVED** [review]

**Comment by Lofty-Brambles** [comment]
Waiting for 1 hour to merge

**Review by JoshDevHub — APPROVED** [review]
lgtm :rocket:

**Pull request merged**
