### PR TITLE
Scaffold out a Rails backend

### LINKED ISSUE #28: Bootstrap a Basic Hello World Ruby Server
We need a Ruby server setup for our backend. This will exist under a new directory, `/backend`

### PR DESCRIPTION
**Pull request by JoshDevHub**
## Because
We need a backend.

## This PR
- Builds a basic API Rails project scaffold with PostgreSQL as the database
- Adds rubocop with the performance, rails, and rspec extensions for linting. Includes an (imo) sane default config that removes things like frozen string checks and enforces double quote strings everywhere, etc.
- Adds basic RSpec setup for testing

## Issue
Closes #28 

## Other Information
I didn't alter any of the other defaults from `rails new` in an API setup. We may or may not need some of the other Rails libraries down the road (ie. ActionMailer), but I figured it'd be fine to kick that proverbial can down the road.

### CODE REVIEW

**Comment by Lofty-Brambles** [comment]
Would it be cool if we had a Rubocop gh action run in parallel to the prettier action in the other PR #25?

**Comment by crespire** [comment]
For authorization, I suggest we use the Pundit gem. I have a ton of exposure to Pundit, which is why I recommend it, but would be open to CanCanCan as well.

**Comment by JoshDevHub** [comment]
> Would it be cool if we had a Rubocop gh action run in parallel to the prettier action in the other PR #25?

Yes it would. I could probably add that into this PR.



> For authorization, I suggest we use the Pundit gem. I have a ton of exposure to Pundit, which is why I recommend it, but would be open to CanCanCan as well.
> 
> I think we should figure out some auth gem candidates if we're doing token only. Devise JWT exists, but I'm not really sure of other options.
> 
> I have used `rodauth-rails`, but would not recommend it as it ends up adding a layer over Rails which complicates things conceptually.
> 
> [edit] Just catching up on reading and saw this: https://github.com/doorkeeper-gem/doorkeeper seems interesting.

I'm for Pundit, which I have a little exposure with from CASA. I have no exposure to CanCanCan, and I doubt anyone else on the project does.

And yeah still kicking around ideas for JWT stuff. I'll definitely check out doorkeeper.

I probably think that authentication/authorization can come along in PRs separate from this one. It's definitely something we'll have to confront early though.

**Comment by JoshDevHub** [comment]
Alright I think I have a finalized github action for linting. I expect we'll add more to it later (tests, etc.). Once again I'll squash some of those commits after review and before merge. Getting it to work  with the monorepo structure was a bit annoying :upside_down_face:

**Review by crespire — APPROVED** [review]
Everything looks good to me. I didn't scrutinize many files, but I did look at the gemfile and the workflow/rubocop stuff and it looks good.

Assuming other files were just Rails generated, but call out if there's a specific file you made changes to.

**Comment by JoshDevHub** [comment]
@crespire Yeah it's probably good to get factorybot and faker up. I think it's fine to wait until there are actual models though.

Most everything was Rails generated yeah. Probably the main exception is `config/initializers/generators.rb` where I've configured how RSpec generators should be run (ie only generate model and request specs), but that's about the only thing.

I'll hit merge on this for now and get into writing some docs and creating the issue on authentication so we have a place to discuss and pool some research together regarding a good solution for that.

**Pull request merged**
